jobs:
  build-branches:
    environment:
      Harbor_Git_Tag: 'v2.7.2'
    machine: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build a container image
          command: |
            bash build-harbor-aarch64.sh
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker images
            bash get-images.sh
            docker save $(docker images --format "{{.Repository}}:{{.Tag}}" | grep "^goharbor/") -o all-in-one/harbor_images_aarch64.tar
            cd all-in-one
            docker build -t alanpeng/harbor_images_aarch64:$Harbor_Git_Tag .
            docker push alanpeng/harbor_images_aarch64:$Harbor_Git_Tag

  build-tags:
    environment:
      Harbor_Git_Tag: 'v2.7.2'
    machine: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build a container image
          command: |
            bash build-harbor-aarch64.sh
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker images
            bash get-images.sh
            docker save $(docker images --format "{{.Repository}}:{{.Tag}}" | grep "^goharbor/") -o all-in-one/harbor_images_aarch64.tar
            cd all-in-one
            docker build -t alanpeng/harbor_images_aarch64:$Harbor_Git_Tag .
            docker push alanpeng/harbor_images_aarch64:$Harbor_Git_Tag
workflows:
  version: 2
  build-for-branches:
    jobs:
      - build-branches
  build-for-tags:
    jobs:
      - build-tags:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
